import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from '../contexts/CartContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce by Anant",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg", // Path to your favicon file in the public directory
  }
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" />
        
        {/* Add more meta tags here if needed */}
      </head>
      
      <body className={inter.className}>
      <CartProvider>
          {children}
        </CartProvider>
        </body>
    </html>
  );
}
